apiVersion : apps/v1
kind: Deployment
metadata:
  name: dstselector 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dstselector
  template:
    metadata:
      labels:
        app: dstselector 
    spec:
      containers:
        - name: dstselector 
          image: containerregistry4pd7i.azurecr.io/dstselector
          ports:
          - containerPort: 80